language: node_js
node_js:
- '12.6.0'
script:
- npm run prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "s20ul26XjhXsBkYH+c+MgUbrBei+9uuAEIlHttPIQggE87/2Gidg55+yztagyitNMciWUjiDYBnbl4usoPiCJBp/X9l2RYQI4sRD1Fjl2LmLQtnlwjW2O65EJ+1GYDUVzoxE0a2ZsyryG7mioclkXRagPlRP3TLZi2pkvlVphlKuV5Q/4FzRVwPYaSLgzqEP1qVBhM9HCjAWdLfInQ/EzjYbSzj72REzP5cpx5m5oFAOavCwLyC1lUKHjTwI+mS0LHz0yYjvrmtFZrwbo6AhQ/3n0eOpGYvpazvVoMJBs3Wwolr9uIEFo+O7SnuXTigewaJ1TdRIxHobuOTisFzot/lnRH23sx7K4v9aIs5L4PFclVpCglUGbgr5ymAyScohQYPI18ZNAoUWc/XVrwJvminvo1gja+GtAKC5lyhYdhSYlQc6vgx+jfQBMOMBLXB9HHAtDh3UBS06eSGlYckto2HiO8I+drghC9VXWChNlMfY5ZlSLDBObhN8d9uMXW1zEOOd/oxCvjH2bznygmZobYQWFHY1fib43JTR0aOCtYfCQR/i1Jq4P0jlCY1v/vkPdtVZB043QnNjELFaqwDdU4OLyi+escksr+d3ombo2yc5K4ZOyhHAAa1ZbxkhCXh4CZexCi7gm+UGldWjOVParMMzBPH4PNk67baE2v9+FHk="
message: "Automatic deployment by travis - CI"